### ISSUE TITLE
Bug with new file PC

### ISSUE THREAD

**Issue by GeoGiam** [grahame-student/OSE#1]
Hi Dasaan,

I can't mod a new save file (pc version), I get: 
runtime error 9
subscript out of range
I start a new game an save inside the cell.
Any idea?

I have been thinking to move this to .Net for pc versions, I could not open anyway your project with my old VB6 sp6

Cheers,

George

**Comment by ghost** [comment]
If you could supply a copy of the save file I'll take a look at the issue.

As for moving the code to .NET you're welcome to as long as you follow the GPL license requirements. 

What goes wrong when you try to open the VB6 project file? Any error messages, etc?

**Comment by GeoGiam** [comment]
how can i send you my file?

**Comment by ghost** [comment]
Unfortunately Github only allows images to be attached to an issue at this point in time. However you could use a file hosting service, such as GoogleDocs or Mediafire, and then leave a link to the file in a comment.

**Comment by GeoGiam** [comment]
Hi Dasaan,

You can download the file here:   http://www.georgebaxter.net/downloads/
Thanks for your help.

Regards,

George

**Comment by ghost** [comment]
I've just updated to version 0.1.8 which allowed me to open your save file.

The new version will complain about FormIDs a bit as I was in the middle of adding in player inventory handling. Just skip through the message boxes and you'll be able to edit your save file.

Did you ever manage to open the VB project? Would like to get to the bottom of that one too.

**Comment by ghost** [comment]
Going to close this bug, reopen if you have any problems.

**Comment by GeoGiam** [comment]
Hello Dasaan, it works. Thanks.

Just some suggestions: 
When I click the image I get and error of wrong path and kaputt.
Your installation file is hard to download, you should better not use blank spaces on it.
In the open dialog box probably you may include extension .ess.

Regards, George

**Comment by ghost** [comment]
Glad it worked for you.
I've looked at the other points you've raised:
1) Installer created a directory with the wrong name (should be Screenshot, not Screenshots) [fixed]
2) The installation file was much easier to download before Github dropped downloading files. I'll have to take a look at a file hosting site, or move to a source control site that does [todo]
3) Added *.ess to the filter list [fixed]

In the future could you please drop each idea / bug report into a separate issue, it would make tracking the issues more efficient.

Thanks :)
